// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function FavNote(arg1, arg2) {
  return window['go']['main']['App']['FavNote'](arg1, arg2);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['App']['RenameNote'](arg1, arg2);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
